New Source: SamuraiScan
TheNetsky/extensions-generic-0.8 pull request #39
Opened 2023-08-15 22:14 UTC by seitenca

task list of needed fixes:
- [x] manga descriptions are not displayed
- [x] broken home section "Completed"

2023-08-16 14:19 UTC, TheNetsky commented
I think it would be better to make an override for mangaDetails as well instead of changing the base, unless you can find more examples where the change of the default description selector has to be changed.

2023-08-16 20:03 UTC, seitenca commented
> I think it would be better to make an override for mangaDetails as well instead of changing the base, unless you can find more examples where the change of the default description selector has to be changed.
> 
👍
> By the looks they seem to have change more on the mangaDetails page, so you sure this all works now?

Yes, yesterday was working, can't test it now
I'm on vacation rn I'll be back on Friday

2023-08-19 11:18 UTC, TheNetsky requested changes

2023-08-19 11:18 UTC, TheNetsky commented on src/SamuraiScan/SamuraiScan.ts
>      override hasAdvancedSearchPage = true
You can remove this, since it has been changed within the generic with last commit.

2023-08-19 11:55 UTC, merged